version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: top-api.mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: top-api.app
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017/
      - NODE_ENV=production
    ports:
      - '3000:3000'
